#This layout inspired by popular fantasy games
title:
  x: 90
  y: 90
  width: 635
  height: 50
  align: center

art:
  x: 75
  y: 150
  width: 675
  height: 520

description:
  x: 100
  y: 675
  width: 625
  height: 275
  valign: middle
  align: center
  font_size: 18
desc: # alias
  extends: description

type:
  x: 90
  y: 955
  width: 645
  height: 50
  align: center

lower_right:
  x: 675
  y: 975
  width: 75
  height: 75
  font_size: 18
  valign: bottom
  align: right
lr: #alias
  extends: lower_right

lower_left:
  x: 100
  y: 800
  width: 256
  height: 256
  font_size: 128
  valign: top
  align: left
ll: # alias
  extends: lower_left

copyright:
  x: 75
  y: 1025
  width: 675
  height: 25
  font_size: 16
  align: center
  valign: bottom
#aliases for copyright
copy:
  extends: copyright
credit:
  extends: copyright
credits:
  extends: copyright



flavor:
  x: 37.5
  y: 37.5
  width: 750
  height: 650
  stroke_width: 10

flavor-safe:
  x: 75
  y: 75
  width: 675
  height: 575
  radius: 16
  dash: 3 3

flavor-pos:
  x: 90
  y: 90
  width: 675
  height: 50
  align: center



cost:
  x: 37.5
  y: 687.5
  width: 375
  height: 400
  stroke_width: 10

cost-safe:
  x: 75
  y: 725
  width: 300
  height: 325
  radius: 16
  dash: 3 3

cost-pos:
  font_size: 128
  x: 75
  y: 740
  width: 300
  height: 325
  align: center


effect:
  x: 412.5
  y: 687.5
  width: 375
  height: 400
  stroke_width: 10

effect-safe:
  x: 450
  y: 725
  width: 300
  height: 325
  radius: 16
  dash: 3 3

variable-pos:
  font_size: 32
  x: 450
  y: 740
  width: 300
  height: 325
  align: center

effect-pos:
  font_size: 64
  x: 450
  y: 800
  width: 300
  height: 325
  align: center



# The "cut line", without rounded corners
cut:
  x: 37.5
  y: 37.5
  width: 750
  height: 1050

# The "safe zone" as defined by TheGameCrafter poker cards
safe:
  x: 75
  y: 75
  width: 675
  height: 975
  radius: 16
  dash: 3 3